import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { startServer } from '../src/server/create-server.mjs';

const reportPath = resolve('data/live-validation.json');
const receiptsPath = resolve('data/live-validation-receipts.json');
mkdirSync(resolve('data'), { recursive: true });
mkdirSync(resolve('output/playwright'), { recursive: true });
if (existsSync(reportPath)) throw new Error('A live validation batch is already retained. Review that report; do not overwrite it or rerun automatically.');
const report = { startedAt: new Date().toISOString(), status: 'running', profile: 'projects-amazon', modelId: 'amazon.nova-micro-v1:0', region: 'us-east-1', maximumCalls: 20, authorizedBudgetUsd: 1, checks: [] };
writeFileSync(reportPath, JSON.stringify(report, null, 2), { flag: 'wx' });
let runtime;
let browser;
try {
  runtime = await startServer({ port: 0 });
  const available = await runtime.model.availability();
  if (!available.available) throw new Error(available.message);
  const initialCalls = runtime.store.budget().attemptedCalls;
  report.startingCalls = initialCalls;
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  await page.goto(runtime.origin);
  await page.getByTestId('item-client-portal').waitFor();
  const session = await (await page.request.get(`${runtime.origin}/api/workspace`)).json();
  report.sessionId = session.sessionId;
  const chat = async message => {
    const before = runtime.store.messages(session.sessionId).length;
    await page.getByLabel('Message your work companion').fill(message);
    const responseWait = page.waitForResponse(response => response.url().endsWith('/api/chat') && response.request().method() === 'POST', { timeout: 120000 });
    await page.getByRole('button', { name: 'Send message', exact: true }).click();
    const response = await responseWait;
    const data = await response.json();
    if (!response.ok()) throw new Error(data.error?.message ?? 'Live conversation failed.');
    assert.ok(data.trace.some(value => value.tool === 'get_briefing' && !value.error), 'Every live turn must establish fresh MCP facts.');
    assert.ok(runtime.store.messages(session.sessionId).length > before);
    return data;
  };
  await chat('Read the workspace and explain what can move forward today. Do not propose a change yet.');
  report.checks.push({ name: 'Live Bedrock conversation reads real MCP workspace facts', passed: true });
  const proposal = await chat('For the client portal, propose changing only nextAction to exactly: Ask Jordan for the approved welcome copy tomorrow. Do not change its owner or blocker.');
  const pending = proposal.workspace.proposals.find(value => value.status === 'pending');
  assert.ok(pending); assert.equal(pending.itemId, 'client-portal');
  assert.deepEqual(pending.changes, { nextAction: 'Ask Jordan for the approved welcome copy tomorrow.' });
  assert.equal(runtime.store.getWorkItem(session.sessionId, 'client-portal').nextAction, 'Ask Jordan for the final welcome copy.');
  await page.getByRole('button', { name: /Confirm action/ }).waitFor();
  await page.screenshot({ path: resolve('output/playwright/live-proposal.png'), fullPage: true });
  report.checks.push({ name: 'Model proposal preserves the original item pending confirmation', passed: true });
  await page.getByRole('button', { name: /Confirm action/ }).click();
  await page.getByText('Decision saved. The work item now shows your confirmed change.').waitFor();
  await page.reload(); await page.getByTestId('item-client-portal').waitFor();
  assert.equal(runtime.store.getWorkItem(session.sessionId, 'client-portal').status, 'active');
  assert.equal(runtime.store.history(session.sessionId).length, 1);
  const updated = await chat('Read the current workspace and report the exact client portal next action. Do not propose another change.');
  assert.ok(updated.text.includes('Ask Jordan for the approved welcome copy tomorrow.'));
  report.checks.push({ name: 'Human confirmation persists through refresh and the next live briefing', passed: true });
  const cancelTurn = await chat('Read the workspace and propose changing only the owner of the mobile sign-in work item to Morgan. Prepare a proposal, but do not apply it.');
  const cancelled = cancelTurn.workspace.proposals.find(value => value.status === 'pending');
  assert.ok(cancelled); assert.equal(cancelled.itemId, 'sign-in'); assert.deepEqual(cancelled.changes, { owner: 'Morgan' });
  await page.getByRole('button', { name: 'Cancel proposal', exact: true }).click();
  await page.getByText('Proposal cancelled. The work item is unchanged.').waitFor();
  assert.equal(runtime.store.getWorkItem(session.sessionId, 'sign-in').owner, 'Taylor');
  assert.equal(runtime.store.briefing(session.sessionId).revision, 2);
  report.checks.push({ name: 'Cancellation preserves the real item and workspace revision', passed: true });
  await page.getByRole('tab', { name: /^Decisions/ }).click();
  await page.screenshot({ path: resolve('output/playwright/live-confirmed-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: resolve('output/playwright/live-confirmed-mobile.png'), fullPage: true });
  await context.close();
  report.budget = runtime.store.budget();
  report.callsInBatch = report.budget.attemptedCalls - initialCalls;
  assert.ok(report.callsInBatch <= 20); assert.ok(report.budget.estimatedCostUsd + report.budget.reservedUsd <= 1); assert.equal(report.budget.uncertainCalls, 0);
  report.status = 'passed';
} catch (error) {
  report.status = 'failed';
  report.failure = String(error.message).slice(0, 1200);
  if (runtime) report.budget = runtime.store.budget();
  process.exitCode = 1;
} finally {
  report.finishedAt = new Date().toISOString();
  if (runtime) writeFileSync(receiptsPath, JSON.stringify(runtime.store.receipts(), null, 2));
  writeFileSync(reportPath, JSON.stringify(report, null, 2));
  if (browser) await browser.close();
  if (runtime) await runtime.close();
  const { sessionId, ...summary } = report;
  console.log(JSON.stringify(summary, null, 2));
}
